### ISSUE TITLE
Shopify API

### ISSUE THREAD

**Issue by ak3zaidan** [Kuuuube/Shopify_Stock_Checker#2]
Hello, thanks for open sourcing this code. I'm currently in the process of building a Shopify bot that buys items from Shopify stores. I'm making it because I want to learn Golang and doing a project with the language is the best way to learn it, but also because a bot like this would be useful to me. I'm having some trouble figuring out the Shopify API flow and how to actually make the API requests. If you have any knowledge with this I'd appreciate some help. If you're interested in helping I can definitely pay you, just reach out to me at ak3zaidan@gmail.com. Thanks.

**Comment by Kuuuube** [comment]
This tool doesn't use shopify's official api. It can be seen as a scraper.

The flow for this tool is quite simple:

1. Read in a list of user defined product urls
2. Transform these urls into the product data urls (.js json files)
3. Read those in and figure out what is and isnt in stock vs what the user's url wants to check
4. Check the previously stored stock state "database" to see if the item exists there, is already known to be in stock, or was last shown out of stock
5. Send a notification through a discord webhook if it went from out of stock -> in stock

If you want to see what it does to the url to pull out the product data, check the value of this variable https://github.com/Kuuuube/Shopify_Stock_Checker/blob/main/discord_webhook_script/check_shopify_stock_webhook.py#L20.

If you only want to deal with the official shopify api, this is not what you are looking for. I imagine shopify has examples on how to use their api.

**Comment by ak3zaidan** [comment]
@Kuuuube thanks for the heads up. Yea I got it to work. It actually gets the stock for a good amount of stores! But some stores return "None" for the stock quantity, assuming the store blocks checking stock count. Also when I mentioned Shopify flow I was referring to the process of actually using the Shopify API to buy products, I just wanted to know if you had any knowledge with that.

**Comment by Kuuuube** [comment]
I don't have any experience with automated purchasing or botted purchasing. Personally I think that gets a bit unethical as those tools are often used by scalpers to snatch products for resell. Good luck on your project and I hope it is used responsibly.

I'm going to close this as it seems to be sorted out now.
